blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/vasmarfas/YoutubeDownloaderNoPolitycs/wiki
    about: Find usage guides and frequently asked questions.
  - name: 🗨 Discussions
    url: https://github.com/vasmarfas/YoutubeDownloaderNoPolitycs/discussions/new
    about: Ask and answer questions.
